### ISSUE TITLE
python library?

### ISSUE THREAD

**Issue by Austinthemighty** [adafruit/Adafruit_Si7021#1]
Is there a python library for this, if now how would i make one?

**Comment by tannewt** [comment]
Python for the Raspberry Pi? Or CircuitPython?

**Comment by Austinthemighty** [comment]
pi, although circuit python would be nice too

**Comment by tannewt** [comment]
I don't have one for the Pi but heres one for CircuitPython: https://github.com/adafruit/Adafruit_CircuitPython_SI7021
