### ISSUE TITLE
Humidity value is getting reported above 100%

### ISSUE THREAD

**Issue by bkrajendra** [adafruit/Adafruit_Si7021#10]
Im just using latest library as it is with ESP8266. What i observed is humidity is crossing 100 value and is being reported as 101 and above.

Its currently raining outside but I guess RH value is never beyond 100.
Please help.

**Comment by bkrajendra** [comment]
As per the datasheet, RH may be reported more than 100 if its closer to 100 due to accuracy curve of sensor. 

![image](https://user-images.githubusercontent.com/994083/62414708-d3d8bb00-b63c-11e9-822f-7ee564305c10.png)


This need to be handled in software by rounding/truncating value to 100.
This can also be done inside library. Or else will do it in my code.

**Comment by ladyada** [comment]
thanks - please submit a PR so that RH returned does not go above 100%

**Comment by caternuson** [comment]
Please try the 1.2.1 version of the library when it becomes available.

**Comment by caternuson** [comment]
Closing due to lack of response.
