### ISSUE TITLE
Unused variable in the library

### ISSUE THREAD

**Issue by Bytesforus** [adafruit/Adafruit_Si7021#20]
...\Arduino\libraries\Adafruit_Si7021_Library\Adafruit_Si7021.cpp: In member function 'float Adafruit_Si7021::readHumidity()':
...\Arduino\libraries\Adafruit_Si7021_Library\Adafruit_Si7021.cpp:88:15: warning: unused variable 'chxsum' [-Wunused-variable]
       uint8_t chxsum = _wire->read();
               ^
...\Arduino\libraries\Adafruit_Si7021_Library\Adafruit_Si7021.cpp: In member function 'float Adafruit_Si7021::readTemperature()':
...\Arduino\libraries\Adafruit_Si7021_Library\Adafruit_Si7021.cpp:121:15: warning: unused variable 'chxsum' [-Wunused-variable]
       uint8_t chxsum = _wire->read();

**Comment by caternuson** [comment]
fixed with #23
