### ISSUE TITLE
using with I2C multi sensors board CCS811 + SI7021 + BMP280 

### ISSUE THREAD

**Issue by KirinDenis** [adafruit/Adafruit_Si7021#21]
I use multi I2C sensors board (CCS811 + SI7021 + BMP280)
(like this https://arduino.ua/prod3768-modyl-datchikov-kachestva-vozdyha-ccs811--si7021--bmp280)

First I'm try using Marcus Sorensen <marcus@electron14.com> library, but it is not work stable for my sensors board. 

Secondary I try to using this Adafruit_Si7021 it is work properly for I2C address 0x40, only after I re-code begin() method like this

`
bool Adafruit_Si7021::begin() {
  _wire->begin();

  _wire->beginTransmission(_i2caddr);
  _wire->endTransmission();

  reset();

  _readRegister8(SI7021_READRHT_REG_CMD);

  readSerialNumber();
  _readRevision();

  return true;
}
`
**I know it is all wrong way!** But like temporary solution it is possible to use and I hope it is helps to developers.

Additional:
After some loops counts the sensor is lost bus... so if temperature or humidity values is NAN, just call begin() method.

like this
`
float temperature =  sensor.readTemperature();
  if (temperature == NAN)
  {
     Serial.println("Si7120 reset");
     sensor.begin();
     float temperature =   sensor.readTemperature();
  }
  Serial.print("Humidity:    ");
  Serial.print(sensor.readHumidity(), 2);
  Serial.print("\tTemperature: ");
  Serial.println(temperature, 2);
`

**Comment by caternuson** [comment]
This behavior is only with the combination of sensors?

**Comment by caternuson** [comment]
Closing due to lack of response. Can try the 1.5.0 release of the library to see if it helps:
https://github.com/adafruit/Adafruit_Si7021/releases/tag/1.5.0
