### ISSUE TITLE
unify with bme280 (no issue, Feature reguest)

### ISSUE THREAD

**Issue by pilnikov** [adafruit/Adafruit_Si7021#24]
I would like to unify this with bme280
like so
`/*!`
`* @brief Sets up the HW by reseting It, reading serial number and reading`
`* revision.`
`* @return Returns true if set up is successful.`
`*/`
`bool Adafruit_Si7021::begin(uint8_t addr, TwoWire *theWire) {`
`delete i2c_dev;`
`i2c_dev = new Adafruit_I2CDevice(addr, theWire);`
`if (!i2c_dev->begin())`
`return false;`
`return init();`
`}`
``
`/*!`
`* @brief Initialise sensor with given parameters / settings`
`* @returns true on success, false otherwise`
`*/`
`bool Adafruit_Si7021::init() {`
``
`if (_readRegister8(SI7021_READRHT_REG_CMD) != 0x3A)`
`_writeRegister8(SI7021_WRITERHT_REG_CMD, 0x3A);`
` if (_readRegister8(SI7021_READRHT_REG_CMD) != 0x3A) return false;`
`readSerialNumber();`
`_readRevision();`
``
`return true;`
`}`

and this check
`if (_readRegister8(SI7021_READRHT_REG_CMD) != 0x3A)`
why?
Copyright?

**Comment by caternuson** [comment]
The two libraries may have slightly different methods, but should be able to be used together. What issue does changing this library solve?

**Comment by pilnikov** [comment]
`if (!i2c_dev->begin()) return false;`
this construct returned false
Wire initialization was performed incorrectly

**Comment by caternuson** [comment]
If you are having trouble initializing the senor, then it may be hardware related. It's probably better to post about this in the forums with photos of your setup:
https://forums.adafruit.com/

**Comment by pilnikov** [comment]
`Adafruit_Si7021 si = Adafruit_Si7021();`
old constructor stopped working

**Comment by pilnikov** [comment]
of course it could have been done that way
`Adafruit_Si7021 si = Adafruit_Si7021(&Wire);`
but there is already a working one
`if (!bme.begin(in_data.bm_addr, &Wire))`
hence the offer

**Comment by caternuson** [comment]
> Adafruit_Si7021 si = Adafruit_Si7021();
> old constructor stopped working

The issue title says "no issue", but it sounds like there is an issue? How is it not working? What does "stopped working" mean? Can you provide more details? What is the most simple example that demonstrates the issue?

**Comment by pilnikov** [comment]
#include "Adafruit_Si7021.h"

bool enableHeater = false;
uint8_t loopCnt = 0;

Adafruit_Si7021 sensor = Adafruit_Si7021();

void setup() {
  Serial.begin(115200);

  // wait for serial port to open
  while (!Serial) {
    delay(10);
  }

  Serial.println("Si7021 test!");
  
  if (!sensor.begin()) {
    Serial.println("Did not find Si7021 sensor!");
    while (true)
      ;
  }

on esp8266(32) this will not work

..................................................................................................................................

#include "Adafruit_Si7021.h"
#define sda_pin 4
#define scl_pin 5

bool enableHeater = false;
uint8_t loopCnt = 0;

Adafruit_Si7021 sensor = Adafruit_Si7021(&Wire);

void setup() {
  Serial.begin(115200);

  // wait for serial port to open
  while (!Serial) {
    delay(10);
  }

  Serial.println("Si7021 test!");
  
  Wire.begin(sda_pin, scl_pin);
  if (!sensor.begin()) {
    Serial.println("Did not find Si7021 sensor!");
    while (true)
      ;
  }

it works

**Comment by pilnikov** [comment]
if (_readRegister8(SI7021_READRHT_REG_CMD) != 0x3A)
this does not work too
Why?
What for?

**Comment by caternuson** [comment]
What does "will not work" mean? Are you getting compile time errors? Does it compile and run but produce error messages at run time? Does it run but the values are wrong? What exactly is happening that "will not work"?

Those code listing for both examples are incomplete sketches. If you provide a complete sketch we can test here to see if the problem can be reproduced.

**Comment by pilnikov** [comment]
1) Standart .ino .cpp .h 

11:06:38.909 -> ets Jun  8 2016 00:22:57
11:06:38.909 -> 
11:06:38.909 -> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
11:06:38.909 -> configsip: 0, SPIWP:0xee
11:06:38.909 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
11:06:38.909 -> mode:DIO, clock div:1
11:06:38.909 -> load:0x3fff0030,len:1240
11:06:38.909 -> load:0x40078000,len:13012
11:06:38.909 -> load:0x40080400,len:3648
11:06:38.909 -> entry 0x400805f8
11:06:39.003 -> Si7021 test!
11:06:39.003 -> Did not find Si7021 sensor!

2) with Wire.begin(sda, scl)

11:17:47.426 -> ets Jun  8 2016 00:22:57
11:17:47.426 -> 
11:17:47.426 -> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
11:17:47.426 -> configsip: 0, SPIWP:0xee
11:17:47.426 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
11:17:47.426 -> mode:DIO, clock div:1
11:17:47.426 -> load:0x3fff0030,len:1240
11:17:47.426 -> load:0x40078000,len:13012
11:17:47.426 -> load:0x40080400,len:3648
11:17:47.426 -> entry 0x400805f8
11:17:47.519 -> Si7021 test!
11:17:47.566 -> Did not find Si7021 sensor!


3) with Wire.begin() & check user register consistency

11:19:25.843 -> ets Jun  8 2016 00:22:57
11:19:25.843 -> 
11:19:25.843 -> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
11:19:25.843 -> configsip: 0, SPIWP:0xee
11:19:25.843 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
11:19:25.843 -> mode:DIO, clock div:1
11:19:25.843 -> load:0x3fff0030,len:1240
11:19:25.843 -> load:0x40078000,len:13012
11:19:25.843 -> load:0x40080400,len:3648
11:19:25.843 -> entry 0x400805f8
11:19:25.937 -> Si7021 test!
11:19:25.983 -> user register...2
11:19:25.983 -> Did not find Si7021 sensor!


4) with Wire.begin() & !check user register consistency

11:21:24.226 -> ets Jun  8 2016 00:22:57
11:21:24.226 -> 
11:21:24.226 -> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
11:21:24.226 -> configsip: 0, SPIWP:0xee
11:21:24.226 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
11:21:24.226 -> mode:DIO, clock div:1
11:21:24.226 -> load:0x3fff0030,len:1240
11:21:24.226 -> load:0x40078000,len:13012
11:21:24.226 -> load:0x40080400,len:3648
11:21:24.226 -> entry 0x400805f8
11:21:24.320 -> Si7021 test!
11:21:24.367 -> user register...2
11:21:24.367 -> Found model Unknown Rev(0) Serial #321154040
11:21:24.367 -> Humidity:    3.33	Temperature: 26.68
11:21:25.445 -> Humidity:    3.33	Temperature: 26.68
11:21:26.523 -> Humidity:    3.33	Temperature: 26.68

////////////////////////////////////////////////////////////////////////////////////////

.ino = https://github.com/adafruit/Adafruit_Si7021/blob/master/examples/si7021/si7021.ino
.h = https://github.com/adafruit/Adafruit_Si7021/blob/master/Adafruit_Si7021.h
.cpp = https://github.com/adafruit/Adafruit_Si7021/blob/master/Adafruit_Si7021.cpp

////////////////////////////////////////////////////////////////////////////////////////
cpp modify:
  
  byte ur = _readRegister8(SI7021_READRHT_REG_CMD);
  Serial.print("user register...");
  Serial.println(ur, HEX);

 // if (ur != 0x3A)
  //  return false;


/////////////////////////////////////////////////////////////////////////////////////////
ino modify:

void setup() {
  Serial.begin(115200);

  // wait for serial port to open
  while (!Serial) {
    delay(10);
  }
  Wire.begin(23, 22);  // --------------------- added --------------------------
  Serial.println("Si7021 test!");

  if (!sensor.begin()) {
    Serial.println("Did not find Si7021 sensor!");
    while (true)
      ;
  }

///////////////////////////////////////////////////////////////////////////////

mcu = esp32dev module
sensor = htu21(made in china)
sda = 23
scl = 22

**Comment by ladyada** [comment]
could be bad hardware, please email the people you ordered the parts from for help!

**Comment by caternuson** [comment]
FWIW...

Tested `si7021.ino` library example:
https://github.com/adafruit/Adafruit_Si7021/blob/master/examples/si7021/si7021.ino

on a Feather ESP8266:
![feather_esp8266_test](https://user-images.githubusercontent.com/8755041/138130017-e435edf5-1c5f-44aa-a686-17b81a3c5ea9.jpg)

works as expected:
![Screenshot from 2021-10-20 09-09-11](https://user-images.githubusercontent.com/8755041/138130321-b7e47bd3-aa62-4fe0-8f60-0a2d7e62a5a8.png)

**Comment by caternuson** [comment]
Feather ESP32 also works.

![feather_esp32_test](https://user-images.githubusercontent.com/8755041/138131825-e94de6d9-44ff-4b4c-aa64-dd9b217c867a.jpg)

![Screenshot from 2021-10-20 09-16-23](https://user-images.githubusercontent.com/8755041/138131863-1526919f-e259-4c3a-81b3-708086c490ce.png)

**Comment by pilnikov** [comment]
Then in the text of your library, please indicate that the library works only with proprietary Adafruit modules
