### ISSUE TITLE
readSerialNumber writes both sections of the serial number to the same location

### ISSUE THREAD

**Issue by angusgbishop** [adafruit/Adafruit_Si7021#25]
Lines 166 and 175 seem to be copied. Line 175 should read 

sernum_b = uint32_t(buffer[0]) << 24 | uint32_t(buffer[1]) << 16 |

Otherwise sernum_a is overwritten with both parts of the serial number, and sernum_b remains 0.

https://github.com/adafruit/Adafruit_Si7021/blob/265050357b80fe6c4f4b926a8800e9edeafc2ed8/Adafruit_Si7021.cpp#L175

**Comment by caternuson** [comment]
Thanks! Good catch. Looks like copy pasta. Want to submit a PR fix? Agree it's just a simple change to `sernum_b`.

**Comment by ladyada** [comment]
PR was closed so i re-did it as a mini patch, no PR

**Comment by caternuson** [comment]
@ladyada thanks!

@angusgbishop that PR looked OK. not sure why it was closed.
